### ISSUE TITLE
Code generated isnt formatted

### ISSUE THREAD

**Issue by andreprawira** [alexy201/awsdocsgpt#1]
i'm not sure if the tool is supposed to be able to generate codes as well but ive tried asking it to generate CDK using Python codes and it is not formatted properly. I attached a screenshot
![image](https://github.com/alexy201/awsdocsgpt/assets/42351199/f2a06835-6fe9-4ff7-b2e7-54d8a71951ee)

**Comment by alexy201** [comment]
Thank you for bringing this to our attention—yes, the tools is supposed to generate code as well. We're currently working on a fix for the formatting issue.

**Comment by alexy201** [comment]
This should be fixed now
