### ISSUE TITLE
Seems broken

### ISSUE THREAD

**Issue by jfr992** [alexy201/awsdocsgpt#3]
<img width="1419" alt="Screen Shot 2023-07-07 at 8 05 11 AM" src="https://github.com/alexy201/awsdocsgpt/assets/68261131/0116917d-849e-4d16-bd57-512dc5275a67">

**Comment by alexy201** [comment]
Thanks for bringing this to our attention. Yes, the site was down a few days ago due to high load reasons. We have since improved our database pooling and connections logic.

**Comment by yogeek** [comment]
/reopen

seems down again, can you confirm please @alexy201  ?
