### ISSUE TITLE
Running frontend locally failed

### ISSUE THREAD

**Issue by kaonmir** [alexy201/awsdocsgpt#5]
Hello @alexy201 . I am really happy to see your awesome project!

By the way I tried to run this project locally, but it failed. The reason was "@/lib/... module not found" error.

And I found `/lib` listed in the .gitignore file.

This might be a dumb question, but is the lib directory missing?

```typescript
// Module not found: Can't resolve '@/lib/settings'
import { getSettings } from "@/lib/settings"
```

**Comment by alexy201** [comment]
Hey @kaonmir you're totally right! Apologies for the missing directory—its just been added back in. Good catch!
