### ISSUE TITLE
No response to simple questions

### ISSUE THREAD

**Issue by yogeek** [alexy201/awsdocsgpt#9]
![Screenshot_2023-08-02-23-21-52-53_40deb401b9ffe8e1df2f1cc5ba480b12.jpg](https://github.com/alexy201/awsdocsgpt/assets/9500406/b583976c-4622-4e14-9ec6-59dd5cb20406)

![Screenshot_2023-08-02-23-22-38-93_40deb401b9ffe8e1df2f1cc5ba480b12.jpg](https://github.com/alexy201/awsdocsgpt/assets/9500406/caf22523-62c8-4593-a495-0b73c13a75cb)

**Comment by alexy201** [comment]
Please @yogeek check that your OpenAI key is a valid key. If this issue still persists, let me know!

**Comment by yogeek** [comment]
@alexy201 I just generated an API key twice and same result.

However, I only have a free openai account : is it supposed to work anyway?

**Comment by redkashmir7** [comment]
@alexy201  I've gotten the same results with a valid API Key.

<img width="1433" alt="image" src="https://github.com/alexy201/awsdocsgpt/assets/74319214/6143ae86-0cff-4885-9978-c31764bef58f">

**Comment by Aub-C** [comment]
Same here. I have a valid API Plus key and I cannot get it to give me a response.

**Comment by 094459** [comment]
I am seeing the same thing, again I created a fresh API key.

**Comment by shreyas-iyer** [comment]
should be resolved now. We were hitting an issue with reaching a spend limit on our OpenAI API key.
